`r if(knitr:::is_latex_output()) '\\startappendices'`

`r if(!knitr:::is_latex_output()) '# (APPENDIX) Appendix {-}'`

# Notation {-}

| Expression | Description                               |
|:----------:|-------------------------------------------|
|    $\C$    | Set of the complex numbers                |
|    $\N$    | Set of the natural numbers                |
|   $\N_0$   | Set of the natural numbers including zero |
|    $\Q$    | Set of the rational numbers               |
|    $\R$    | Set of the real numbers                   |

## Linear Algebra {-}

| Expression | Description                |
|:----------:|----------------------------|
|  $\dim S$  | Dimension of $S$           |
|   $N(A)$   | Null space of $A$          |
|   $R(A)$   | Range of $A$               |
|  $\rk A$   | Rank of $A$                |
|   $I_n$    | $n$-by-$n$ identity matrix |

## Real Analysis and Topology {-}

|            Expression             | Description                              |
|:---------------------------------:|------------------------------------------|
|          $\interior(S)$           | Interior of $S$                          |
|           $\closure(S)$           | Closure of $S$                           |
|           $\partial S$            | Boundary of $S$                          |
| $\varphi : X \rightrightarrows Y$ | Correspondence $\varphi$ from $X$ to $Y$ |
|            $\convex S$            | Convex hull of $S$                       |

## Statistics {-}

|                     Expression                      | Description                                                                                                 |
|:---------------------------------------------------:|-------------------------------------------------------------------------------------------------------------|
|                     $a \perp b$                     | The random variables $a$ and $b$ are independent                                                            |
|                 $a \perp b \mid c$                  | They are conditionally independent given $c$                                                                |
|                       $P(a)$                        | A probability distribution over a discrete variable                                                         |
|                       $p(a)$                        | A probability distribution over a continuous variable, or over a variable whose type has not been specified |
|                     $a \sim P$                      | Random variable $a$ has distribution $P$                                                                    |
|     $E_{\mathrm{x}\sim P} [f(x)]$ or $E[f(x)]$      | Expectation of $f(x)$ with respect to $P(\mathrm{x})$                                                       |
|                    $\Var(f(x))$                     | Variance of $f(x)$ under $P(\mathrm{x})$                                                                    |
|                 $\Cov(f(x), g(x))$                  | Covariance of $f(x)$ and $g(x)$ under $P(\mathrm{x})$                                                       |
| $\Norm (\mathbf{x}; \mathbf{\mu}, \mathbf{\Sigma})$ | Gaussian distribution over $\mathbf{x}$ with mean $\mathbf{\mu}$ and covariance $\mathbf{\Sigma}$           |
|                      $\mu_n'$                       | $n$th (raw) moment of a distribution                                                                        |
|                       $\mu_n$                       | $n$th central moment of a distribution                                                                      |
|                    $X_n \dlim X$                    | $X_n$ converges in distribution to $X$                                                                      |
|                    $X_n \plim X$                    | $X_n$ converges in probability to $X$                                                                       |
|                    $X_n \rlim X$                    | $X_n$ converges in the $r$th mean to $X$                                                                    |
|                    $X_n \mlim X$                    | $X_n$ converges in quadratic mean to $X$                                                                    |

# Probability Distributions {-}

::: {.rmdcaution}
**This section is still in development**
:::

## Discrete {-}
### Bernoulli {-}
### Binomial {-}
### Geometric {-}
### Hypergeometric {-}
### Negative Binomial {-}
### Poisson {-}
### Uniform {-}

## Continuous {-}
### Beta {-}
### Cauchy {-}
### Chi Squared {-}
### Dirac {-}
### Exponential {-}
### F {-}
### Gamma {-}
### Laplace {-}
### Normal {-}
### Student T {-}
### Uniform {-}
### Weibull {-}



<!-- Discrete distributions -->
<!--
<div id="bernoulli"></div>
<div id="binomial"></div>
<div id="geometric"></div>
<div id="hypergeometric"></div>
<div id="negbin"></div>
<div id="poisson"></div>
<div id="uniformDiscrete"></div>
-->

<!-- Continuous distributions -->
<!--
<div id="beta"></div>
<div id="cauchy"></div>
<div id="chisq"></div>
<div id="exponential"></div>
<div id="centralF"></div>
<div id="gamma"></div>
<div id="normal"></div>
<div id="studentt"></div>
<div id="uniform"></div>
<div id="weibull"></div>
-->

<!-- Discrete distributions -->
<!--
<script src="/figures/bernoullijs"></script>
<script src="/figures/binomialjs"></script>
<script src="/figures/geometricjs"></script>
<script src="/figures/hypergeometricjs"></script>
<script src="/figures/negbinjs"></script>
<script src="/figures/poissonjs"></script>
<script src="/figures/uniformDiscretejs"></script>
-->

<!-- Continuous distributions -->
<!--
<script src="/figures/betajs"></script>
<script src="/figures/cauchyjs"></script>
<script src="/figures/centralFjs"></script>
<script src="/figures/chisqjs"></script>
<script src="/figures/exponentialjs"></script>
<script src="/figures/gammajs"></script>
<script src="/figures/normaljs"></script>
<script src="/figures/studenttjs"></script>
<script src="/figures/uniformjs"></script>
<script src="/figures/weibulljs"></script>
-->

# Estimators {-}

::: {.rmdcaution}
**This section is still in development**
:::
